name: rock_paper_scissors
description: A Rock Paper Scissors Game which is build on flutter and can run on Android, IOS, Web, Windows, MacOS and Linux

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.8


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/hands/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 700
          style: italic


